// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateKey(arg1) {
  return window['go']['main']['App']['CreateKey'](arg1);
}

export function DeleteKey(arg1) {
  return window['go']['main']['App']['DeleteKey'](arg1);
}

export function GetExpiringKeys(arg1) {
  return window['go']['main']['App']['GetExpiringKeys'](arg1);
}

export function GetKeys(arg1) {
  return window['go']['main']['App']['GetKeys'](arg1);
}

export function IsLoggedIn() {
  return window['go']['main']['App']['IsLoggedIn']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function Register(arg1, arg2) {
  return window['go']['main']['App']['Register'](arg1, arg2);
}

export function UpdateKey(arg1) {
  return window['go']['main']['App']['UpdateKey'](arg1);
}
