// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateKey(arg1:models.CreateKeyRequest):Promise<void>;

export function DeleteKey(arg1:number):Promise<void>;

export function GetExpiringKeys(arg1:number):Promise<Array<models.APIKeyDTO>>;

export function GetKeys(arg1:models.KeyFilter):Promise<Array<models.APIKeyDTO>>;

export function IsLoggedIn():Promise<boolean>;

export function Login(arg1:string,arg2:string):Promise<void>;

export function Logout():Promise<void>;

export function Register(arg1:string,arg2:string):Promise<void>;

export function UpdateKey(arg1:models.UpdateKeyRequest):Promise<void>;
